In [1]:
import numpy as np
print(np.__version__)

1.26.4


#  creating array in numpy and checking its properties

In [20]:
a=np.array([1,3,4,8,9])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 3 4 8 9]
(5,)
int32
1
5
4


# Acessing and asigning values in the array

In [27]:
a=np.array([1,3,4,8,9])
print(a[0])
# assigning the values of the 0 index to another value
a[0]=20
print(a)

b=a*np.array([2,3,6,7,1])
print(b)

1
[20  3  4  8  9]
[40  9 24 56  9]


# Difference between python list and array

In [32]:
l=[1,2,3]
m=[2,3,4]
dot=0
for i in range(len(l)):
    dot+=l[i]*m[i]
print(dot)


20


# in numpy it is calculated faster and in one line


In [41]:
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.dot(a,b)
print(c)

newdot=a@b
print(newdot)

20
20


# Multidimensional Array

In [62]:
a=np.array([[2,3,4],[4,5,7]])
print(a.shape)
print(a)
print(a.size)
print(a[0][1])
print(a[0,1])
#SLicing of the md array
print(a[:,2])
print(a[0,:])

(2, 3)
[[2 3 4]
 [4 5 7]]
6
3
3
[4 7]
[2 3 4]


# Applying different properties of the multidimensional array 

In [79]:
a=np.array([[2,3,4],[4,5,7],[5,3,7]])
# finding the inverse of the matrix // note for finding the inverse of the matrix square matrix should be there
print(np.linalg.inv(a))
# finding the transpose of the matrix
print(a.T)
print(np.linalg.det(a))
#finding the diagnol of the matrix
c=np.diag(a)

print(np.diag(c))

[[-4.66666667  3.         -0.33333333]
 [-2.33333333  2.         -0.66666667]
 [ 4.33333333 -3.          0.66666667]]
[[2 4 5]
 [3 5 3]
 [4 7 7]]
-2.9999999999999982
[[2 0 0]
 [0 5 0]
 [0 0 7]]


# checking the boolean


In [94]:
a=np.array([[2,3],[4,6],[1,3]])
print(a)

# check if the number in the array is greater than 3 then print 0
check= a>3
print(check)
# in one line easy way also it can be done such as
print(a[a>3])

b=np.where(a>3,a,0)
print(b)


[[2 3]
 [4 6]
 [1 3]]
[[False False]
 [ True  True]
 [False False]]
[4 6]
[[0 0]
 [4 6]
 [0 0]]


# Fancy indexing

In [97]:
a=np.array([2,5,7,8,9,5,1,6])
b=[2,4,7]
print(a[b])

[7 9 6]


# Common usecase of it


In [102]:
a=np.array([2,3,4,8,10,11,16,14])
even=np.argwhere(a%2==0).flatten()
print(a[even])

[ 2  4  8 10 16 14]


# Creating sequence 

In [16]:
# printing the first 5 odd number using arange keyword
a=np.arange(1,10,2)
print(a)
b=np.arange(2,10,2)
print(b)
c=np.arange(1,10)
print(c)



[1 3 5 7 9]
[2 4 6 8]
[1 2 3 4 5 6 7 8 9]


# Reshaping the arrays

In [29]:
a=np.arange(1,9)
print(a)
b=a.reshape((2,4))
print(b)
print(b.shape)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


# BroadCasting 


In [34]:
a=np.array([[2,4,5],[2,0,8],[5,7,8]])
b=np.array([1,1,1])
c=a+b
print(c)

[[3 5 6]
 [3 1 9]
 [6 8 9]]


# Some functions used in the data science for future

In [39]:
a=np.array([[1,2,5,7,8,9,12],[40,23,1,7,8,9,55]])
print(a)

[[ 1  2  5  7  8  9 12]
 [40 23  1  7  8  9 55]]


In [61]:
print(a.sum())
print(a.sum(axis=None))  #by default the axis will be none
print(a.sum(axis=0))     #when axis=0 it will sum the elements of the column (vertical sum)
print(a.sum(axis=1))     # when axis=1 it will sum the elements of the row   (horizontal sum)
print(a.mean(axis=0))    # it will find the mean of the column
print(a.std())           # it will find the standard deviation of the following data
print(a.var())           # it will print the variance of the following data
print(a.min(axis=0))     # it will print the min value between the columns
print(a.min(axis=1))   # it will print the min values between the rows
##### same wise the max function can also be used to find the maximum value between the column and the rows



187
187
[41 25  6 14 16 18 67]
[ 44 143]
[20.5 12.5  3.   7.   8.   9.  33.5]
15.163900472867144
229.9438775510204
[ 1  2  1  7  8  9 12]
[1 1]


In [71]:
a=np.array([1.0,2.0],dtype=np.int64)
print(a)
print(a.dtype)

[1 2]
int64


# Revison and new concepts


# Single dimension array

In [21]:
import numpy as np
n1=np.array([10,20,30,40])
n1
n1.shape
n1.ndim
n1.itemsize

4

# Multidemensional Array


In [28]:
a=np.array([[1,2,3],[2,3,4],[8,9,7]])
a
a.ndim
a.shape


(3, 3)

# initialize the numpy arrays with zeros

In [34]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
b=np.full((3,3),7)
b

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

# Initializing the numpy with range

c=np.arange(1,10)
c

# Skip the numbers

In [44]:
d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

# initialize with the random number

In [50]:
e=np.random.randint(100,100000,5)
e

array([11975, 64397, 25892, 54933,  5628])

# initialization the array shape changes in a fraction of second

In [58]:
f=np.array([[1,2,3],[4,5,7],[8,9,4],[8,3,3]])
f

array([[1, 2, 3],
       [4, 5, 7],
       [8, 9, 4],
       [8, 3, 3]])

In [60]:
f.shape

(4, 3)

In [66]:
f.shape=(3,4)
f

array([[1, 2, 3, 4],
       [5, 7, 8, 9],
       [4, 8, 3, 3]])

# joining the numpy array


In [73]:
a=np.array([10,20,30])
b=np.array([30,40,50])
np.vstack((a,b)) #it will add vertically means column wise
np.hstack((a,b))  # it will addd all in horizontal

array([10, 20, 30, 30, 40, 50])

In [75]:
a=np.array([1,2,4])
b=np.array([5,7,3])
c=np.array([3,0,40])
d=np.array([10,22,44])
np.vstack((a,b,c,d))


array([[ 1,  2,  4],
       [ 5,  7,  3],
       [ 3,  0, 40],
       [10, 22, 44]])

In [77]:
np.hstack((a,b,c,d))

array([ 1,  2,  4,  5,  7,  3,  3,  0, 40, 10, 22, 44])

# numpy intersection and difference