In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.copy()
c=a.view()
c[1]=20
b[0]=10
print(c)
print(b)
print(a)

[ 1 20  3  4  5  6]
[10  2  3  4  5  6]
[ 1 20  3  4  5  6]


In [7]:
a=np.array([1,2,3,4,5,6])
print(a[a>2])


[3 4 5 6]


# numpy intersection and difference

In [10]:
x=np.array([10,20,50,60,89,12,133,44,55,66,77,89,10])
y=np.array([20,30,40,10,50,70,80,20,11,22,44,88,90])
np.intersect1d(x,y)

array([10, 20, 44, 50])

# difference

In [13]:
x=np.array([10,20,50,60,89,12,133,44,55,66,77,89,10])
y=np.array([20,30,40,10,50,70,80,20,11,22,44,88,90])
np.setdiff1d(x,y)

array([ 12,  55,  60,  66,  77,  89, 133])

# Addition of the numpy

In [16]:
t=np.array([40,90])
s=np.array([99,86])
np.sum([t,s])

315

In [18]:
np.sum([t,s],axis=0) # it will add the rowssss

array([139, 176])

In [20]:
np.sum([t,s],axis=1)  # it will add the columns

array([130, 185])

# array mathematics

In [23]:
p=np.array([20,30,40])
p+1

array([21, 31, 41])

In [25]:
p/2

array([10., 15., 20.])

In [27]:
p*2

array([40, 60, 80])

In [31]:
p**len(p)

array([ 8000, 27000, 64000], dtype=int32)

# numpy maths functions

In [34]:
a=np.array([2,30,50,80,90,12,14,16])
np.mean(a)

36.75

In [36]:
np.median(a)

23.0

In [38]:
np.std(a)

31.015117281738593

In [40]:
np.var(a)

961.9375

In [46]:
b=np.array([10,20,30,40,50,60])
c=(b[4]-np.mean(b))/np.std(b)
c


0.8783100656536798

# Saving and loading numpy array

In [49]:
n11=np.array([10,20,30,40,60,80])
np.save('my_name',n11)


In [51]:
np.load('my_name.npy')

array([10, 20, 30, 40, 60, 80])

# linespace

In [56]:
import numpy as np
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

help(np.linspace)

# Uniform samples


In [61]:
np.random.uniform(5,10,size=4)

array([7.87427376, 5.80609356, 5.76558868, 5.79401061])

In [63]:
np.random.uniform(size=5)

array([0.21452677, 0.51648311, 0.78925918, 0.79885866, 0.94313557])

In [65]:
np.random.uniform(size=(2,3))

array([[0.92966276, 0.47554574, 0.82677431],
       [0.86894765, 0.94977244, 0.45943504]])

In [67]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

# identity matrix

In [70]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
a=np.array([20,40,80,90,44,66,77,22,22,30])
np.min(a)

20

In [74]:
np.max(a)

90

In [85]:
np.unique(a,return_counts=True)

(array([20, 22, 30, 40, 44, 66, 77, 80, 90]),
 array([1, 2, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [87]:
a=np.array([-0.7,0.4,2,2.4,4.7,5.3])
bins=np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 3, 3, 4, 4], dtype=int64)

# Expand dimension

In [90]:
arr=np.array([8,14,5,6,77,90,23,14,15,18])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  5,  6, 77, 90, 23, 14, 15, 18]])

In [92]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 5],
       [ 6],
       [77],
       [90],
       [23],
       [14],
       [15],
       [18]])

# squeeze

In [97]:
arr=np.array([[8],[12],[22],[60],[21],[9],[90]])
np.squeeze(arr)

array([ 8, 12, 22, 60, 21,  9, 90])

In [103]:
a=np.array([0,0,0,1,2,3,4,5,0,0])
np.count_nonzero(a)


5

# argwhere (anywhere)

In [106]:
arr=np.array([1,1,1,0,0,0,2,2,2])
np.argwhere(arr)

array([[0],
       [1],
       [2],
       [6],
       [7],
       [8]], dtype=int64)

In [112]:
arr=np.array([[0.12,0.64,0.19,0.05]])
np.argmax(arr)
np.argmin(arr)

3

In [114]:
# sorting
arr=np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

In [118]:
SA=np.array([[1,-3,4],[-2,-4,8]])
np.abs(SA)

array([[1, 3, 4],
       [2, 4, 8]])

# clip

In [121]:
arr=np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

# round

In [128]:
arr=np.array([0.44,0.878787,0.555,1.888])
np.round(arr,decimals=0)

array([0., 1., 1., 2.])

# replacing values inside array

In [133]:
a=np.array([1,3,4,5,7,8,9])
a[np.where(a>5)]

array([7, 8, 9])

# Put

In [8]:
arr=np.array([1,2,3,5,7,8,9])
np.put(arr,[1,2],[6,7])
arr



array([1, 6, 7, 5, 7, 8, 9])

# copy to

In [140]:
arr1=np.array([1,2,3])
arr2=np.array([4,7,9])
print("before arr1",arr1)
print("before arr2",arr2)
np.copyto(arr1,arr2)
print("after arr1",arr1)
print("after arr2",arr2)

before arr1 [1 2 3]
before arr2 [4 7 9]
after arr1 [4 7 9]
after arr2 [4 7 9]


# extracts unique elements from both arrays

In [144]:
a=np.array([1,4,6,7,9])
b=np.array([3,6,7,21,10])
np.setxor1d(a,b)

array([ 1,  3,  4,  9, 10, 21])

# Union

In [147]:
a=np.array([1,4,6,7,9])
b=np.array([3,6,7,21,10])
np.union1d(a,b)

array([ 1,  3,  4,  6,  7,  9, 10, 21])

# Splitting

In [150]:
A=np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [159]:
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

# Compairing two arrrays

In [162]:
a=np.array([0.25,0.4,0.6,0.32])
b=np.array([0.26,0.3,0.7,0.32])
tolerance=0.1
np.allclose(a,b,tolerance)

False

# Repeat

In [182]:
np.repeat('2017',3)

# np.repeat(1,3)


array(['2017', '2017', '2017'], dtype='<U4')

# TIle

In [180]:
np.tile("Ram",5)

array(['Ram', 'Ram', 'Ram', 'Ram', 'Ram'], dtype='<U3')

In [184]:
np.tile(3,(2,3))

array([[3, 3, 3],
       [3, 3, 3]])

# Einstein summation convection

In [187]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(21,30).reshape(3,3)
np.einsum('ii->i',a) #### it will extract the diagnols

array([1, 5, 9])

# Histogram

In [190]:
A=np.array([[3,4,5,2],
           [6,7,2,6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1], dtype=int64),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))

In [192]:
a=np.array([[2,4,6],[3,8,12]])
np.percentile(a,50)

5.0

# Show floats with two decimal values

In [195]:
np.set_printoptions(precision=2)
a=np.array([12.23456,32.34535])
print(a)

[12.23 32.35]


# prints arrays to its max

In [203]:

np.set_printoptions(threshold=np.inf)

# Increase the number of elements in a line

In [201]:

np.set_printoptions(linewidth=100)


# Einsteion summation

In [5]:
a=np.array([1,2,3])
print(np.einsum('i->',a))

## 2.Element wise multiplication and summation
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.einsum('i,i->',a,b))

##3.oter product
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.einsum("i,j->ij",a,b))

## 4 tranpose matrix

A=np.array([[2,3,4],[8,9,30]])
print(np.einsum('ij->ji',A))

## 5. matrix vector multiplication
A=np.array([[1,2],[5,6],[7,9]])
x=np.array([7,9])
print(np.einsum('ij,j->i',A,x))

## 6.matrix multiplication

A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[7,8]])
print(np.einsum('ij,jk->ik',A,B))

#7 Trace of matrix
A=np.array([[1,2],[3,4]])
print(np.einsum('ii->',A))




6
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 2  8]
 [ 3  9]
 [ 4 30]]
[ 25  89 130]
[[18 21]
 [40 47]]
5


# understanding the batch multiplication vector

In [19]:
A=np.array([
            [[2,3],[6,7],[9,3]],  ## first batch dimension is 3*2
           [[4,6],[2,9],[4,4]]
            ])                    ## second batch dimension is 3*2)
B=np.array([
            [[3,4,7],[1,2,4]],     ## first batch dimension is 2*3                          
            [[5,4,3],[2,7,5]]])    ## second batch dimension is 2*3
C=np.matmul(A,B)
C

array([[[ 9, 14, 26],
        [25, 38, 70],
        [30, 42, 75]],

       [[32, 58, 42],
        [28, 71, 51],
        [28, 44, 32]]])

In [25]:
C = np.einsum('bij,bjk->bik', A, B)
C

array([[[ 9, 14, 26],
        [25, 38, 70],
        [30, 42, 75]],

       [[32, 58, 42],
        [28, 71, 51],
        [28, 44, 32]]])

# Understanding the tensor contraction 

In [44]:
A=np.random.rand(2,3,4)

B=np.random.rand(4,5,6)
C=np.tensordot(A,B,axes=([2],[0]))

D=np.einsum('ijk,klm->ijlm',A,B)
D

array([[[[0.50985822, 0.79623369, 0.96984655, 0.73667671, 0.18024845,
          0.52416744],
         [0.61590517, 0.22742884, 0.6028719 , 0.57933892, 0.4133302 ,
          0.61496568],
         [0.93136924, 0.32049507, 0.47409067, 1.06810235, 0.57508714,
          0.8234003 ],
         [0.17798776, 0.27557799, 0.59414164, 0.56127332, 0.90566576,
          0.88410312],
         [0.54700884, 0.61115361, 0.67692621, 0.4531912 , 0.2834897 ,
          0.78311482]],

        [[1.81298863, 1.82899882, 2.44574223, 1.63261948, 1.0629124 ,
          1.47837954],
         [2.07720999, 0.9117031 , 1.68261005, 1.78422922, 1.64927075,
          2.13817403],
         [2.13785231, 0.62060886, 1.46584841, 2.53958515, 2.25152049,
          2.16004811],
         [1.13405962, 0.97909331, 1.05035644, 1.82030984, 2.30076415,
          2.39800691],
         [1.92903098, 1.71307032, 1.58666263, 1.47447421, 0.81680055,
          1.40470087]],

        [[1.32416725, 1.53150173, 1.91040326, 1.3274762 , 0.531412